<!-- ajax -->
@include('profile.includes.ajax')
@include('users.includes.ajax')
@include('companies.includes.ajax')
@include('routes.groups.includes.ajax')
@include('routes.routes.includes.ajax')
@include('menu.menu.includes.ajax')
@include('menu.menu-item.includes.ajax')
@include('permissions.includes.ajax')
@include('departments.includes.ajax')
@include('inventories.inventory-categories.includes.ajax')
@include('inventories.inventories.includes.ajax')
@include('residents.includes.ajax')

<!-- modals -->
@include('profile.includes.modals')
@include('users.includes.modals')
@include('companies.includes.modals')
@include('routes.groups.includes.modals')
@include('routes.routes.includes.modals')
@include('menu.menu.includes.modals')
@include('menu.menu-item.includes.modals')
@include('departments.includes.modals')
@include('inventories.inventory-categories.includes.modals')
@include('inventories.inventories.includes.modals')
@include('residents.includes.modals')

<!-- validate -->
@include('profile.includes.validate')
@include('users.includes.validate')
@include('companies.includes.validate')
@include('routes.groups.includes.validate')
@include('routes.routes.includes.validate')
@include('menu.menu.includes.validate')
@include('menu.menu-item.includes.validate')
@include('permissions.includes.validate')
@include('departments.includes.validate')
@include('inventories.inventory-categories.includes.validate')
@include('inventories.inventories.includes.validate')
@include('residents.includes.validate')
